name: Java CI com JDK 17, 21 e 25

on:
  push:
    branches: [ "main", "master", "feature/**" ]
  pull_request:
    branches: [ "main", "master", "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17', '21', '25']

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: â˜• Config Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: ğŸ—ï¸ Compilar e Testar com Maven
        run: mvn clean install
