name: SonarCloud Analysis

on:
  push:
    branches: [ "main", "master", "feature/**" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para análise de histórico e PRs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recomendado para versões atuais do Sonar

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=dsaltoe_hash-pass
          -Dsonar.organization=dsaltoe
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.qualitygate.wait=true

#  sonarqube:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          # Disabling shallow clones is recommended for improving the relevancy of reporting
#          fetch-depth: 0
#      - name: SonarQube Scan
#        uses: SonarSource/sonarqube-scan-action@v7 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#
#
#      - name: Check Quality Gate
#        uses: sonarsource/sonarqube-quality-gate-action@v1
#        timeout-minutes: 5
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}